Issue 20 and 3 - bump versions minio postgres and added documentation
fredrikhgrelland/terraform-nomad-hive pull request #23
Opened 2020-10-09 09:38 UTC by claesgill

Closes #20 
Closes #3 

- Bumped versions minio and postgres
- Added documentation

2020-10-09 11:12 UTC, zhenik requested changes

2020-10-09 11:12 UTC, zhenik commented on README.md
> +Minio should be available at [localhost:9000](http://localhost:9000/minio/).
I think this part should be different. How to verify hive setup

2020-10-09 11:16 UTC, claesgill commented on README.md
> +Minio should be available at [localhost:9000](http://localhost:9000/minio/).
Yes, you are probably right. Do you have any suggestions?

2020-10-09 11:22 UTC, zhenik commented on README.md
> +Minio should be available at [localhost:9000](http://localhost:9000/minio/).
You need query tables via beeline and consul proxy. Hint here https://github.com/zhenik-poc/big-data-stack-practice#useful-commands-debug

2020-10-09 11:23 UTC, claesgill commented on README.md
> +Minio should be available at [localhost:9000](http://localhost:9000/minio/).
Alright, thanks!

2020-10-12 07:29 UTC, zhenik commented on README.md
> +4. Run `SHOW databases;`. Your output should look something like this:
```suggestion
4. Run `SHOW databases;`. Your output should look like this:
```

2020-10-12 07:33 UTC, zhenik approved these changes

2020-10-12 07:55 UTC, dangernil approved these changes

2020-10-12 08:28 UTC, merged